server:
  port: 8002

spring:
  application:
    name: 配置管理
  profiles:
    active: dev

seamohai:
  name: 申陌海
  job: 学生

student:
  name: 张三
  age: 10
  email:
  birthday:
  hobbies:
    - 篮球
    - 编程
    - 阅读
  scores:
    chinese: 90
    math: 95
    english: 88
  address:
    province: 江苏省
    city: 南京市
  courses:
    - name: 高等数学
      credit: 4
    - name: 大学英语
      credit: 3


app:
  name: 配置管理模块
  author: ${seamohai.name}
  port: 8002
  max-count: 100